### PR TITLE
Fixes for tilt and pedometer functions

### PR DESCRIPTION
**Pull request by ManodyaRasanjana**
Add fixes to address the compile errors on Arduino (Version 2.3.0) related tilt and pedometer functions

Screenshot_2024-02-15 225143

### CODE REVIEW

**Comment by ManodyaRasanjana** [comment]
Closing the push request since editors add the changes manually from their side

**Comment by rbuisson-invn** [comment]
Thanks for reporting the issue: fixed in 1.0.2.
Could you please share the targeted board that was affected by the issue?
(build was ok on Arduino Zero)

**Comment by ManodyaRasanjana** [comment]
> Thanks for reporting the issue: fixed in 1.0.2. Could you please share the targeted board that was affected by the issue? (build was ok on Arduino Zero)

Mentioned issue was observed on "Adafruit Feather nRF52840 Express" and "Seeed XIAO nRF52840" development boards

**Comment by gjabouley-invn** [comment]
> Mentioned issue was observed on "Adafruit Feather nRF52840 Express" and "Seeed XIAO nRF52840" development boards

Thanks @ManodyaRasanjana , can you please confirm the version of `Adafruit Feather nRF52840 Express` board package you are using? latest 1.6.0 ?

**Comment by ManodyaRasanjana** [comment]
> Thanks @ManodyaRasanjana , can you please confirm the version of `Adafruit Feather nRF52840 Express` board package you are using? latest 1.6.0 ?

Yes, board packages are latest versions (sorry I forgot to add the details previously). "Adafruit nRF52 1.6.0" and "Seeed nRF52 boards "1.1.8".

PS: I didn't get a chance to test properly, but there is another error regarding `"#include <string>"` when compile for "Arduino AVR boards (V1.8.6)"

**Pull request closed without merging**
